theme = "doom_acario_dark"

[editor]
bufferline = "always"

[editor.lsp]
auto-signature-help = false

[editor.cursor-shape]
insert = "bar"
normal = "block"

[editor.file-picker]
ignore = false

[keys.normal]
space = { W = ":w"}
D = ["extend_to_line_bounds", "trim_selections", "change_selection"]
